name: Generate Hermes binaries

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  gen-hermes:
    name: "Generate hermes binaries"
    runs-on: ubuntu-latest
    concurrency: gen-hermes
    steps:
      - uses: actions/checkout@v3

      - run: ./scripts/gen-hermes

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: "feat(hermes): update binaries"
          commit-message: "feat(hermes): update binaries"
          body: "After merging this PR, create a release tag based on this pattern: `hermes/<HERMES-BINARY-VERSION>` (Eg: `hermes/v1.8.2`)."
          branch: feat/gen-hermes
          delete-branch: true
