name: Generate GEX binaries

on:
  push:
    branches:
      - main
    paths:
      - 'gex/*.go'
      - 'scripts/gen-gex'

jobs:
  gen-gex:
    name: "Generate gex binaries"
    runs-on: ubuntu-latest
    concurrency: gen-gex
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        if: env.GIT_DIFF
        with:
          go-version: '1.21'

      - run: ./scripts/gen-gex

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: "feat(gex): update binaries"
          commit-message: "feat(gex): update binaries"
          body: ""
          branch: feat/gen-gex
          delete-branch: true
