name: Generate nodetime binaries

on:
  push:
    branches:
      - main
    paths:
      - 'nodetime/*.go'
      - 'scripts/gen-nodetime'
      - 'scripts/data/gen-nodetime/**'
      - '!scripts/data/gen-nodetime/tsconfig.json'

jobs:
  gen-nodetime:
    name: "Generate nodetime binaries"
    runs-on: ubuntu-latest
    concurrency: gen-nodetime
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus2

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: ./scripts/gen-nodetime

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: "feat(nodetime): update binaries"
          commit-message: "feat(nodetime): update binaries"
          body: ""
          branch: feat/gen-nodetime
